services:
    web:
        build:
            context: .
            dockerfile: ./docker/prod-nginx.Dockerfile
        ports:
            - "80:80"
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: ./docker/prod-php.Dockerfile
        environment:
            - DEPLOYMENT_URL=
            - ENVIRONMENT=production